### ISSUE TITLE
State of the project (a.k.a. Will there be any further releases?)

### ISSUE THREAD

**Issue by mateuszkwiecinski** [JakeWharton/dependency-tree-diff#17]
I just stumbled into the issue which turned out to be fixed on the main branch, and it took me a while to find that out. So with the motivation of saving other people's time, can you share if there is a possibility you'll resume publishing new releases of this project? 

I figured it's reasonable to ask after I noticed your other projects received some extra care over the last few months (small things like enabling Renovate or resumed releases of dependency-watch). It would be great if you could share if you plan to revive this project too, and if we can expect further releases anytime soon. 

It just would be great to understand what the current state of this project is, maybe there are things the community can help with?  

Thank you for this tool 🙏

**Comment by JakeWharton** [comment]
I can't promise anything for November, but I'm on pat leave in December so I can definitely pull it off then.

**Comment by JakeWharton** [comment]
1.2.1 out
