### ISSUE TITLE
R8 minification classfile version

### ISSUE THREAD

**Issue by TWiStErRob** [JakeWharton/dependency-tree-diff#64]
Hey, you have this line in your R8 task:

https://github.com/JakeWharton/dependency-tree-diff/blob/1aa9304b9bcadc3e6d47de260e805450ec240754/build.gradle#L72

Do you remember what that means or where that knowledge came from?

I'm asking because I tried setting a higher toolchain and the .class files inside the minified jar are still compatible with whatever the source .jar files were. Each class preserves the same .class file version as the input is.

Related (for my reference): https://github.com/ajalt/mordant/issues/233

**Comment by JakeWharton** [comment]
Probably was a bug. It was for classes that it synthesized like horizontal lambda merges.

![Screenshot_20240929-094315.png](https://github.com/user-attachments/assets/5b5800a5-c866-4168-a483-d14924511b48)

I don't think the Mordant thing is related. FFM is only available starting in JDK 22 so you have to use JDK 22 or newer for the runtime types to be available to R8 to link against.

**Comment by TWiStErRob** [comment]
Oh, thank you for finding a source!

Yeah, the mordant issue is related as in that triggered my question.

I want to support running the R8 result on Java 11+, but use the latest Clikt/mordant. So far based on my tests it seems fine to use JDK 22 for R8.

Re the last sentence in the screenshot, I would hope that for synthetics that do contain bytecode from input, it uses the maximum version of all the inputs whose bytecode ends up in the synthesized class.

**Comment by TWiStErRob** [comment]
I'll close this as there's no issue with this project. Should've opened a discussion 😅.
